#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: ''
      #password 密码
      password: ''
      #address 地址，定位信息
      address: 安徽省合肥市蜀山区合肥工业大学
      #email 接受通知消息的邮箱
      email: 123456789@qq.com
      #school 学校全称
      school: 合肥工业大学
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#  - user:
#      #username 学号或者工号
#      username: ''
#      #password 密码
#      password: ''
#      #address 地址，定位信息
#      address: 安徽省合肥市蜀山区合肥工业大学
#      #email 接受通知消息的邮箱
#      email: 123456789@qq.com
#      #school 学校全称
#      school: 合肥工业大学

Info:
  ServerChan: # 填写Server酱的SCKEY
  Qsmg: # 填写Qsmg酱的SCKEY
  Email:
    enable: true
    server: smtp.163.com # 填写邮件的smtp服务器
    port: 465 # 填写邮件服务器的端口号
    account: '' # 邮件服务器登录用户名
    password: '' # 邮件服务器登录密码
